In [1]:
import numpy as np

A. Buat array 2D berdasarkan 6 digit terakhir NIM

In [2]:
nim_6_digit = [3, 1, 1, 1, 3, 2]

matrix_a = np.array(nim_6_digit).reshape(2, 3)
matrix_b = np.array([6, 5, 4, 3, 2, 1]).reshape(2, 3)

print(f"6 digit terakhir NIM: {nim_6_digit}")
print(f"\nMatrix A (2x3):\n{matrix_a}")
print(f"\nMatrix B (2x3):\n{matrix_b}")

6 digit terakhir NIM: [3, 1, 1, 1, 3, 2]

Matrix A (2x3):
[[3 1 1]
 [1 3 2]]

Matrix B (2x3):
[[6 5 4]
 [3 2 1]]


B. Operasi penjumlahan, pengurangan, dan perkalian matriks

In [3]:
# Penjumlahan
hasil_tambah = matrix_a + matrix_b
print(f"Penjumlahan (A + B):\n{hasil_tambah}")

# Pengurangan
hasil_kurang = matrix_a - matrix_b
print(f"\nPengurangan (A - B):\n{hasil_kurang}")

# Perkalian element-wise
hasil_kali_elem = matrix_a * matrix_b
print(f"\nPerkalian element-wise (A * B):\n{hasil_kali_elem}")

# Perkalian matriks (dot product)
hasil_kali_dot = matrix_a @ matrix_b.T
print(f"\nPerkalian matriks (A @ B^T):\n{hasil_kali_dot}")

Penjumlahan (A + B):
[[9 6 5]
 [4 5 3]]

Pengurangan (A - B):
[[-3 -4 -3]
 [-2  1  1]]

Perkalian element-wise (A * B):
[[18  5  4]
 [ 3  6  2]]

Perkalian matriks (A @ B^T):
[[27 12]
 [29 11]]


C. Konversi matriks menjadi bentuk 1D

In [4]:
flat_a = matrix_a.flatten()
flat_b = matrix_b.flatten()

print(f"Matrix A (1D): {flat_a}")
print(f"Matrix B (1D): {flat_b}")

reshaped_a = matrix_a.reshape(-1)
print(f"\nMatrix A reshape(-1): {reshaped_a}")

Matrix A (1D): [3 1 1 1 3 2]
Matrix B (1D): [6 5 4 3 2 1]

Matrix A reshape(-1): [3 1 1 1 3 2]


D. Slicing pada matriks

In [5]:
print(f"Matrix A asli:\n{matrix_a}")
print(f"\nBaris pertama          (A[0])    : {matrix_a[0]}")
print(f"Baris kedua            (A[1])    : {matrix_a[1]}")
print(f"Kolom pertama          (A[:,0])  : {matrix_a[:, 0]}")
print(f"Kolom kedua            (A[:,1])  : {matrix_a[:, 1]}")
print(f"Elemen baris 0, kolom 2 (A[0,2]): {matrix_a[0, 2]}")
print(f"Slice baris 0, kolom 1-2 (A[0,1:]): {matrix_a[0, 1:]}")
print(f"Seluruh baris, kolom 0-1 (A[:,0:2]):\n{matrix_a[:, 0:2]}")

Matrix A asli:
[[3 1 1]
 [1 3 2]]

Baris pertama          (A[0])    : [3 1 1]
Baris kedua            (A[1])    : [1 3 2]
Kolom pertama          (A[:,0])  : [3 1]
Kolom kedua            (A[:,1])  : [1 3]
Elemen baris 0, kolom 2 (A[0,2]): 1
Slice baris 0, kolom 1-2 (A[0,1:]): [1 1]
Seluruh baris, kolom 0-1 (A[:,0:2]):
[[3 1]
 [1 3]]
